### ISSUE TITLE
Shopify parameters missing, cannot authenticate

### ISSUE THREAD

**Issue by ilrein** [lukeclifton/meteor-shopify-api#1]
Hey @lukeclifton, thanks for the great library. This is exactly my cup of tea. Can you help me get the ball rolling?

I'm never able to authenticate properly...I loaded the init code on the client/server and tried to access the page, only to result in: Shopify parameters missing, cannot authenticate

Here's my code:

```javascript
// client side code:
ShopifyApi.init({
    appUrl:         'http://localhost:3000',
    apiKey:         '7axxxxxxxxxxxxxxxxxxxxxx',
    scopes:         'read_products,read_content',
    shopOverride:   'STORE.myshopify.com'
  });

//SERVER
ShopifyApi.init({
      apiKey:     '7a99xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      secret:     'e7dbxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
       shopOverride: 'STORE.myshopify.com'
  });

//BOTH

Router.onBeforeAction(function() {

    // If not logged in, handle the shopify OAuth login process before anything else
    if (!Meteor.userId()) {
        ShopifyApi.authorizeApp(this.params.query);
    }

    this.next();

}, { only: ['wildfyre'] });

Router.route('/wildfyre'); 
```
What am I doing wrong?

**Comment by lukeclifton** [comment]
Hey @ilrein.

Thanks for your interest this package.

You will need to manually install your app for your specified Shopify shop first...have you done that yet?

If not you can use the app installer package i created for doing this:
https://github.com/lukeclifton/meteor-shopify-app-installer

Sorry theres probably some details missing from the README. Will get this sorted.
